version: '3'
services:
  geth:
    build: ./geth_node
    entrypoint: geth
    command: --dev --rpccorsdomain geth --rpc --rpcaddr "0.0.0.0" --rpcport 8545 --networkid 1324231
    ports:
      - 8545:8545
    # volumes:
    #   - type: volume
    #     source: geth 
    #     target: /root/.ethereum

  webapp:
    build: ./webapp
    depends_on:
      - geth
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - ${ENV}
    restart: always

  zkit:
    build: ./webapp/zerokit
    # environment:
    #   - DEBUG=*
    ports:
      - 4000:3000
# volumes:
#   geth:
# openid_identifier
