version: '3.2'
services:
  geth:
    image: ethereum/client-go
    entrypoint: geth
    command: --dev --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcvhosts "*" --rpcport 8545 --networkid 1324231
    volumes:
      - type: volume
        source: geth 
        target: /root/.ethereum

  eth:
    build: 
      context: .
      dockerfile: Dockerfile-eth
    env_file:
      - .env.dev
    depends_on:
      - geth
    volumes:
        - data:/root/app/eth/data
  
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    command: npm run serve
    ports:
      - 3002:3002
    env_file:
      - .env.dev
    volumes:
      - ./client:/root/app/client
      - /root/app/client/node_modules

  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    command: npm run dev
    depends_on:
      - geth
      - eth
      - client
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    volumes:
      - ./server:/root/app/server
      - /root/app/server/node_modules
      - data:/root/app/server/data



volumes:
  geth:
  data:
