FROM maven:3.3-jdk-8 AS hg-build


COPY . /opt/maven
WORKDIR /opt/maven/
ENTRYPOINT ./build.sh

RUN apt-get update -y && apt-get install haveged -y && update-rc.d haveged defaults

COPY ./hashgraph /opt/maven
COPY ./hashgraph/exo-config.hashgraph.json /opt/maven/exo-config.json
WORKDIR /opt/maven/source/socketdemo
RUN mvn install -e

FROM hg-build
EXPOSE 51200-51299
EXPOSE 50200-50299
EXPOSE 52200-52299
WORKDIR /opt/maven


ENTRYPOINT ["java", "-jar", "swirlds.jar"]