version: '3.2'
services:
  geth:
    image: ethereum/client-go
    entrypoint: geth
    command: --dev --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcvhosts "*" --rpcport 8545 --networkid 1324231
    volumes:
      - type: volume
        source: geth 
        target: /root/.ethereum

  eth:
    build: 
      context: .
      dockerfile: Dockerfile-eth
    env_file:
      - .env
    depends_on:
      - geth
    volumes:
      - data:/root/app/eth/data
  
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    command: npm run build
    env_file:
      - .env
    volumes:
      - ./client:/root/app/client
      - /root/app/client/node_modules
      - dist:/root/app/client/dist

  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    command: npm start
    depends_on:
      - geth
      - eth
      - client
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - data:/root/app/server/data
      - dist:/root/app/server/public

volumes:
  geth:
  data:
  dist:
