version: '3.2'
services:
  geth:
    image: ethereum/client-go
    entrypoint: geth
    command: --dev --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcvhosts "*" --rpcport 8545 --networkid 1324231
    volumes:
      - type: volume
        source: geth 
        target: /root/.ethereum
  
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    command: npm run serve
    ports:
      - 3002:3002
    env_file:
      - .env.dev
    volumes:
      - ./client:/root/app/client
      - /root/app/client/node_modules

  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    command: npm run dev
    depends_on:
      - geth
      - client
    env_file:
      - .env.dev
    ports:
      - 3000:3000
    volumes:
      - ./server:/root/app/server
      - /root/app/server/node_modules
      - data:/root/app/server/data

volumes:
  geth:
  data: