version: '2'
services:
  geth:
    build: .
    ports:
      - "8545:8545"
    volumes:
      # - "./files/geth:/root/.ethereum/geth"
      - "./files/keystore:/root/.ethereum/keystore"
      - "./files/password:/root/.ethereum/password"
